minecraft_version=26.1.2
intermediary_version=0.0.0
loader_version=0.19.3
fabric_version=0.154.0+26.1.2
fabric_kotlin_version=1.13.12+kotlin.2.4.0

mod_version=1.0.6-26.1.2
maven_group=dev.ryan
archives_base_name=skylist
